spring:
  application:
    name: sso-demo
  http:
    converters:
      preferred-json-mapper: gson
server:
  port: 11000
  name: sso-demo
logging:
  config: classpath:logback-spring.xml
  level:
    root: info
    com.siemens: DEBUG