spring:
  application:
    name: sso-demo
  http:
    converters:
      preferred-json-mapper: gson
  datasource:
    url: jdbc:postgresql://192.168.0.105:5432/postgres?tinyInt1isBit=false&useServerPrepStmts=true&cachePrepStmts=true
    type: com.alibaba.druid.pool.DruidDataSource
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
    initial-size: 10
    max-active: 20
    maximum-pool-size: 25
    connection-timeout: 2000
    login-timeout: 3000
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    auto-commit: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=false;druid.stat.slowSqlMillis=5000
  jpa:
    properties:
      hibernate:
        generate_statistics: true
        cache:
          use_second_level_cache: true
          use_query_cache: true
          region:
            factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
      javax:
        persistence:
          sharedCache:
            mode: ENABLE_SELECTIVE
      ddl-auto: none
      dialect: org.hibernate.dialect.PostgreSQLDialect
      naming:
        physical-strategy: com.siemens.csde.sso.config.jpa.MySpringPhysicalNamingStrategy
    show-sql: true
#
  redis:
    host: 192.168.0.105
    port: 6379
    password: 123456
    timeout: 1000
    pool:
      max-idle: 200
      min-idle: 10
      max-active: 1000
      max-wait: 1000
    database: 0
  rabbitmq:
    host: 192.168.0.105
    port: 5672
    username: admin
    password: admin
    publisher-confirms: true
    cache:
      connection:
        mode: channel
    ##    size: 10
      channel:
        size: 1
    listener:
      direct:
        acknowledge-mode: auto
        prefetch: 1
      simple:
#        acknowledge-mode: none
        concurrency: 1
        max-concurrency: 1
        prefetch: 1
  batch:
    job:
      enabled: false
  cloud:
    loadbalancer:
      retry:
        enabled: true
server:
  port: 13464
  #${random.int[10000,19999]}
  name: sso-demo
logging:
  config: classpath:logback-spring.xml
  level:
    root: info
    com.siemens: DEBUG

feign:
  hystrix:
    enabled: false


hystrix:
  threadpool:
    default:
      coreSize: 40
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

ribbon:
  OkToRetryOnAllOperations: true
  MaxAutoRetriesNextServer: 1
  MaxAutoRetries: 3
  ReadTimeout: 5000
  ConnectTimeout: 5000