spring:
  application:
    name: sso-demo
  http:
    converters:
      preferred-json-mapper: gson
  redis:
    host: 192.168.1.47
    port: 6379
    password: 123456
    timeout: 1000
    pool:
      max-idle: 200
      min-idle: 10
      max-active: 1000
      max-wait: 1000
    database: 0
  rabbitmq:
    host: 192.168.1.6
    port: 5672
    username: admin
    password: admin
    publisher-confirms: true
    cache:
      connection:
        mode: channel
      channel:
        size: 20
    listener:
      direct:
        acknowledge-mode: auto
        prefetch: 50
      simple:
        acknowledge-mode: auto
        concurrency: 1
        max-concurrency: 1
        prefetch: 50
  batch:
    job:
      enabled: false
  cloud:
    loadbalancer:
      retry:
        enabled: true
server:
  port: 11000
  name: sso-demo
logging:
  config: classpath:logback-spring.xml
  level:
    root: info
    com.siemens: DEBUG

feign:
  hystrix:
    enabled: false


hystrix:
  threadpool:
    default:
      coreSize: 40
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

ribbon:
  OkToRetryOnAllOperations: true
  MaxAutoRetriesNextServer: 1
  MaxAutoRetries: 3
  ReadTimeout: 5000
  ConnectTimeout: 5000